name: Release

on:
  release:
    types: [published]

env:
  TARGET: Release

jobs:
  package:
    name: Build and Upload Package
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build and Package
        working-directory: Maui.Chips
        run: |
          dotnet build -c Release
      - name: Push to Nuget.org
        working-directory: Maui.Chips
        run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
